//! Writing an intent's implementation out as a Rust crate.
//!
//! The generated crate is deliberately small and readable: one `run`
//! function that calls the same [`plans`](super::plans) function the
//! in-process executor uses, with every parameter spelled out, and one
//! [`export_intent!`](crate::export_intent) line for the C ABI. It is what
//! the library "invented" for the name, in a form a developer can read,
//! copy into their own code, or edit and rebuild.

use super::Plan;

/// The `src/lib.rs` of the crate implementing `name` with `plan`.
pub fn source(name: &str, plan: &Plan) -> String {
    let (description, body, imports) = match plan {
        Plan::Faces { options } => (
            "runs the bundled frontal-face cascade over the region and reports every face, best-supported first".to_string(),
            format!(
                "    plans::find_faces(\n        image,\n        region,\n        &CascadeOptions {{\n            scale_factor: {:?},\n            min_neighbors: {},\n            min_size: {},\n            max_size: {:?},\n        }},\n    )",
                options.scale_factor, options.min_neighbors, options.min_size, options.max_size
            ),
            "use syrup::cascade::CascadeOptions;\n",
        ),
        Plan::ColorBars { color } => (
            format!("finds the {} regions of the region that are much wider than tall", color.name()),
            format!("    plans::find_bars(image, region, {:?})", color.hue()),
            "",
        ),
        Plan::ColorBlobs { color } => (
            format!("finds every {} region, largest first", color.name()),
            format!("    plans::find_blobs(image, region, {:?})", color.hue()),
            "",
        ),
        Plan::TextBlock => (
            "finds the block of text-like pixels".to_string(),
            "    plans::find_text(image, region)".to_string(),
            "",
        ),
        Plan::BarFill { color } => (
            format!("measures how full the largest {} bar is, as a percentage of its track", color.name()),
            format!("    plans::measure_bar(image, region, {:?})", color.hue()),
            "",
        ),
        Plan::Ocr => (
            "reads the region's text through the OCR engine".to_string(),
            "    plans::read_text(image, region)".to_string(),
            "",
        ),
    };
    format!(
        "//! `{name}`, as syrup {version} understood it: {description}.\n\
         //!\n\
         //! Generated by `syrup::intent`. Edit it if you like — it is ordinary Rust\n\
         //! over the library's primitives — or delete the directory to regenerate.\n\
         \n\
         {imports}\
         use syrup::image::RgbaImage;\n\
         use syrup::intent::{{Outcome, plans}};\n\
         use syrup::{{Detection, Rect}};\n\
         \n\
         /// {description_cap}.\n\
         pub fn run(image: &RgbaImage, region: Rect) -> Detection<Outcome> {{\n\
         {body}\n\
         }}\n\
         \n\
         syrup::export_intent!(\"{name}\", run);\n",
        version = env!("CARGO_PKG_VERSION"),
        description_cap = capitalise(&description),
    )
}

/// The `Cargo.toml` of the crate implementing `name`, depending on the
/// syrup sources at `syrup_dir`.
pub fn manifest(name: &str, syrup_dir: &std::path::Path) -> String {
    // Forward slashes keep the manifest valid on every platform, and a
    // literal string avoids escaping the rest.
    let path = syrup_dir
        .to_string_lossy()
        .replace('\\', "/")
        .replace('\'', "");
    format!(
        "[package]\n\
         name = \"{crate}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\
         publish = false\n\
         \n\
         [lib]\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         syrup = {{ path = '{path}' }}\n\
         \n\
         [profile.release]\n\
         codegen-units = 16\n\
         debug = false\n",
        crate = crate_name(name),
    )
}

/// The package name of the crate implementing `name`.
pub fn crate_name(name: &str) -> String {
    format!("syrup_intent_{name}")
}

fn capitalise(text: &str) -> String {
    let mut chars = text.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cascade::CascadeOptions;
    use crate::intent::Color;

    #[test]
    fn generated_source_names_the_plan_and_exports_the_abi() {
        let text = source(
            "find_face",
            &Plan::Faces {
                options: CascadeOptions::default(),
            },
        );
        assert!(text.contains("plans::find_faces("));
        assert!(text.contains("min_neighbors: 3"));
        assert!(text.contains("syrup::export_intent!(\"find_face\", run);"));
        assert!(text.starts_with("//! `find_face`, as syrup"));

        let text = source("measure_red_bar", &Plan::BarFill { color: Color::Red });
        assert!(text.contains("plans::measure_bar(image, region, (340.0, 20.0))"));
    }

    #[test]
    fn manifests_point_back_at_the_library() {
        let text = manifest("find_face", std::path::Path::new("C:\\Users\\dev\\syrup"));
        assert!(text.contains("name = \"syrup_intent_find_face\""));
        assert!(text.contains("syrup = { path = 'C:/Users/dev/syrup' }"));
        assert!(text.contains("crate-type = [\"cdylib\"]"));
    }
}
